### ISSUE TITLE
iterm2 theme support

### ISSUE THREAD

**Issue by avelino** [vic/rebecca-theme#7]

**Comment by vic** [comment]
Hey @avelino , here's my current setup:


https://gist.github.com/vic/fa58918694af3b3767fbc7dc22cbc406

**Comment by vic** [comment]
The iterm2 color theme still needs some work, but if you have an emacs patched with 24bits on terminal it will work regardless of your terminal theme I guess.

**Comment by vic** [comment]
Also there are some rebecca iterm2 color schemes here: https://github.com/martinlindhe/base16-iterm2/tree/master/itermcolors  that look great!

They are generated from [base16-rebecca](https://github.com/vic/base16-rebecca)

**Comment by vic** [comment]
Btw, I've updated the rebecca.itermcolors in the gist, and also added some screenshots of my emacs running on the terminal https://github.com/vic/rebecca-theme/issues/1
